"""Convert the Claude Design data script into a TypeScript locale module.

Faithful extraction: the strings, the Indic digit maps and the tier words are
the design's own, not retyped, so the app and the design cannot drift apart
through a transcription slip. Regenerate rather than editing app.ts by hand.

The design script declares some constants more than once (later blocks
override earlier ones, as they would at runtime), so the LAST definition wins
here too.
"""
import pathlib
import re
import sys

DESIGN = pathlib.Path(
    "C:/Users/vedan/AppData/Local/Temp/claude/c--CODING-ASIH-176/"
    "b69642f7-1cb3-4393-9455-60e860d61d18/scratchpad/design_data.js"
)
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "lib" / "i18n" / "app.ts"

WANTED = ("DIG", "S", "ASKS", "CHECKS", "EV_LABELS", "NOT_MEASURED", "TIER_WORD",
          "LAYERS", "VESSEL_L", "PROFILE_ROWS", "CACHE_ITEMS", "CONTACTS",
          "TABS", "LANGS")

HEADER = '''/**
 * App strings, straight from the Claude Design file (ORCA Simple v3).
 *
 * GENERATED by tools/gen_locale.py from the design's own data script. Not
 * retyped, so the app and the design cannot drift apart through a
 * transcription slip. Regenerate rather than editing by hand.
 *
 * Four locales are complete (en, te, ta, hi). `LANGS` lists every language the
 * picker offers and whether a device voice exists for it; a language with no
 * voice falls back to large text, never to spoken English.
 *
 * `DIG` carries Telugu and Devanagari numerals, because switching language
 * has to change the digits too, not only the words around them.
 *
 * The wording is deliberately plain. "YOU CAN GO" and "The sea is calm today"
 * are what a low-literacy reader on a moving boat can act on; "MODERATE risk,
 * score 30 of 100" is not.
 */

export type LangCode = "en" | "te" | "ta" | "hi" | "or" | "ml" | "kn" | "bn";
'''


def extract(src: str, name: str) -> str | None:
    """The LAST `const NAME = <literal>;` in the script, brace-matched."""
    found = None
    for m in re.finditer(rf"\bconst\s+{name}\s*=\s*([\{{\[])", src):
        start = m.end() - 1
        opener = m.group(1)
        closer = "}" if opener == "{" else "]"
        depth, i, in_str, quote, esc = 0, start, False, "", False
        while i < len(src):
            ch = src[i]
            if in_str:
                if esc:
                    esc = False
                elif ch == "\\":
                    esc = True
                elif ch == quote:
                    in_str = False
            elif ch in "\"'`":
                in_str, quote = True, ch
            elif ch == opener:
                depth += 1
            elif ch == closer:
                depth -= 1
                if depth == 0:
                    found = src[start:i + 1]
                    break
            i += 1
    return found


def main() -> int:
    if not DESIGN.is_file():
        print(f"design data not found at {DESIGN}", file=sys.stderr)
        return 1
    src = DESIGN.read_text(encoding="utf-8")
    parts = [HEADER]
    missing = []
    for name in WANTED:
        body = extract(src, name)
        if body is None:
            missing.append(name)
            continue
        parts.append(f"export const {name} = {body} as const;\n")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT.name}: {len(WANTED) - len(missing)}/{len(WANTED)} constants, "
          f"{OUT.stat().st_size} bytes")
    if missing:
        print("MISSING:", ", ".join(missing), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
