/**
 * App strings, straight from the Claude Design file (ORCA Simple v3).
 *
 * GENERATED by tools/gen_locale.py from the design's own data script. Not
 * retyped, so the app and the design cannot drift apart through a
 * transcription slip. Regenerate rather than editing by hand.
 *
 * Four locales are complete (en, te, ta, hi). `LANGS` lists every language the
 * picker offers and whether a device voice exists for it; a language with no
 * voice falls back to large text, never to spoken English.
 *
 * `DIG` carries Telugu and Devanagari numerals, because switching language
 * has to change the digits too, not only the words around them.
 *
 * The wording is deliberately plain. "YOU CAN GO" and "The sea is calm today"
 * are what a low-literacy reader on a moving boat can act on; "MODERATE risk,
 * score 30 of 100" is not.
 */

export type LangCode = "en" | "te" | "ta" | "hi" | "or" | "ml" | "kn" | "bn";

export const DIG = { te: '౦౧౨౩౪౫౬౭౮౯', hi: '०१२३४५६७८९' } as const;

export const S = {
  en: {
    go: "YOU CAN GO",
    goAdvice: "The sea is calm today. You can go out and stay till evening.",
    seaNow: "Sea right now",
    trips: "My trips",
    lastTrips: "Last 30 days",
    tripsHint: "Tap a trip to see the weather you had",
    hoursOut: "hours out",
    catchLog: "Catch noted",
    addTrip: "Add today’s trip",
    tagline: 'Sea safety advice', langNative: 'English', loc: 'Visakhapatnam coast',
    online: 'Connected · information is fresh', updatedNow: 'Updated 2 min ago',
    caution: 'CAUTION', askOrTap: 'Ask a question, or tap one below',
    hold: 'Hold to speak', type: 'Type', listening: 'Listening', youSaid: 'You are saying',
    heard: 'Can I go fishing today', keepHolding: 'Keep holding while you speak', holding: 'Holding — speak now',
    checking: 'Checking for you', query: 'Can I go fishing today?',
    composing: 'Preparing your answer', checkNote: 'We check the sea, the weather, the sea border, and your boat.',
    advice: 'Waves are rough this morning. If you go, come back before eleven.',
    listenAgain: 'Listen again', why: 'Why this answer?', evidence: 'Where this came from', values: 'values',
    waveL: 'Wave height', windL: 'Wind speed', returnL: 'Come back by',
    sum: 'Total', scoreNote: 'Higher number means more danger',
    band: '40 to 69 means CAUTION. You may go, but return early.',
    layers: 'What to show', mapTitle: 'Map', tapZone: 'Tap a number', forecast: 'Later today',
    profile: 'My boat', boatType: 'Fibre boat', boatNote: 'Advice is matched to this boat. Update it if anything changes.',
    language: 'Language', emergency: 'Emergency', zoneName: 'Spot 1 · East Bank', topPick: 'Best spot today',
    route: 'Show the way',
    voiceNote: 'Odia and Bengali have no voice yet. Answers will be shown in large text instead.',
    tripCache: 'Save this trip on the phone', downloadTrip: 'Save trip', bundledTiles: 'Saved map — works without internet',
    offline: 'No internet', lastUpdate: 'Last updated 40 minutes ago',
    geoTitle: 'BORDER WARNING', geoBody: 'You are close to the sea border. Turn back towards the west now.',
    toBoundary: 'To the border', bearing: 'Direction', ack: 'I understand — turning west',
    noDismiss: 'This message stays until you tap the button.',
    worksOffline: 'WORKS WITHOUT INTERNET', position: 'WHERE YOU ARE NOW',
    nearestHarbour: 'Nearest safe harbour', harbourName: 'Visakhapatnam Fishing Harbour'
  },
  te: {
    go: "వెళ్లొచ్చు",
    goAdvice: "ఈరోజు సముద్రం ప్రశాంతం. వెళ్లొచ్చు, సాయంత్రం వరకు ఉండొచ్చు.",
    seaNow: "ఇప్పుడు సముద్రం",
    trips: "నా ప్రయాణాలు",
    lastTrips: "గత ౩౦ రోజులు",
    tripsHint: "వాతావరణం చూడటానికి ప్రయాణాన్ని నొక్కండి",
    hoursOut: "గంటలు బయట",
    catchLog: "పట్టుబడి నమోదు",
    addTrip: "ఈరోజు ప్రయాణం చేర్చండి",
    tagline: 'సముద్ర భద్రత సలహా', langNative: 'తెలుగు', loc: 'విశాఖపట్నం తీరం',
    online: 'కనెక్ట్ అయ్యింది · సమాచారం తాజాది', updatedNow: '౨ నిమిషాల క్రితం',
    caution: 'జాగ్రత్త', askOrTap: 'ప్రశ్న అడగండి, లేదా కింద ఒకటి నొక్కండి',
    hold: 'మాట్లాడటానికి నొక్కి పట్టుకోండి', type: 'టైప్', listening: 'వింటున్నాను', youSaid: 'మీరు అంటున్నారు',
    heard: 'ఈరోజు చేపల వేటకు వెళ్లొచ్చా', keepHolding: 'మాట్లాడేటప్పుడు నొక్కి ఉంచండి', holding: 'నొక్కి ఉంది — మాట్లాడండి',
    checking: 'మీ కోసం చూస్తున్నాం', query: 'ఈరోజు చేపల వేటకు వెళ్లొచ్చా?',
    composing: 'సమాధానం సిద్ధమవుతోంది', checkNote: 'సముద్రం, వాతావరణం, సరిహద్దు, మీ పడవ — అన్నీ చూస్తాం.',
    advice: 'ఈ ఉదయం అలలు ఎక్కువ. వెళ్తే పదకొండు లోపు తిరిగి రండి.',
    listenAgain: 'మళ్లీ వినండి', why: 'ఎందుకు ఇలా?', evidence: 'ఇది ఎక్కడ నుంచి?', values: 'విలువలు',
    waveL: 'అల ఎత్తు', windL: 'గాలి వేగం', returnL: 'తిరిగి రావాలి',
    sum: 'మొత్తం', scoreNote: 'సంఖ్య ఎక్కువైతే ప్రమాదం ఎక్కువ',
    band: '౪౦ నుంచి ౬౯ = జాగ్రత్త. వెళ్లొచ్చు, కానీ ముందుగా తిరిగి రండి.',
    layers: 'ఏం చూపించాలి', mapTitle: 'మ్యాప్', tapZone: 'ఒక సంఖ్యను నొక్కండి', forecast: 'ఈరోజు తరువాత',
    profile: 'నా పడవ', boatType: 'ఫైబర్ పడవ', boatNote: 'ఈ పడవకు తగినట్టే సలహా ఇస్తాం. మార్పులుంటే సరిచేయండి.',
    language: 'భాష', emergency: 'అత్యవసరం', zoneName: 'స్థలం ౧ · తూర్పు దిబ్బ', topPick: 'ఈరోజు మంచి స్థలం',
    route: 'దారి చూపు',
    voiceNote: 'ఒడియా, బెంగాలీకి వాయిస్ లేదు. సమాధానం పెద్ద అక్షరాలలో చూపుతాం.',
    tripCache: 'ఈ ప్రయాణం ఫోన్‌లో సేవ్ చేయండి', downloadTrip: 'ప్రయాణం సేవ్ చేయండి', bundledTiles: 'సేవ్ చేసిన మ్యాప్ — నెట్ అవసరం లేదు',
    offline: 'ఇంటర్నెట్ లేదు', lastUpdate: '౪౦ నిమిషాల క్రితం అప్‌డేట్',
    geoTitle: 'సరిహద్దు హెచ్చరిక', geoBody: 'మీరు సముద్ర సరిహద్దుకు దగ్గరగా ఉన్నారు. వెంటనే పడమరకు తిరగండి.',
    toBoundary: 'సరిహద్దు దూరం', bearing: 'దిక్కు', ack: 'అర్థమైంది — పడమరకు తిరుగుతాను',
    noDismiss: 'బటన్ నొక్కే వరకు ఈ సందేశం ఉంటుంది.',
    worksOffline: 'నెట్ లేకుండా పనిచేస్తుంది', position: 'మీరు ఇప్పుడు ఉన్న చోటు',
    nearestHarbour: 'దగ్గరి రేవు', harbourName: 'విశాఖపట్నం ఫిషింగ్ హార్బర్'
  },
  ta: {
    go: "போகலாம்",
    goAdvice: "இன்று கடல் அமைதி. போகலாம், மாலை வரை இருக்கலாம்.",
    seaNow: "இப்போது கடல்",
    trips: "என் பயணங்கள்",
    lastTrips: "கடந்த 30 நாள்",
    tripsHint: "வானிலை பார்க்க பயணத்தை தொடவும்",
    hoursOut: "மணி வெளியே",
    catchLog: "மீன் பதிவு",
    addTrip: "இன்றைய பயணத்தை சேர்",
    tagline: 'கடல் பாதுகாப்பு ஆலோசனை', langNative: 'தமிழ்', loc: 'விசாகப்பட்டினம் கடற்கரை',
    online: 'இணைப்பு உள்ளது · தகவல் புதியது', updatedNow: '2 நிமிடம் முன் புதுப்பிப்பு',
    caution: 'எச்சரிக்கை', askOrTap: 'கேள்வி கேளுங்கள், அல்லது கீழே ஒன்றை தொடவும்',
    hold: 'பேச அழுத்திப் பிடிக்கவும்', type: 'தட்டச்சு', listening: 'கேட்கிறேன்', youSaid: 'நீங்கள் சொல்வது',
    heard: 'இன்று மீன்பிடிக்கப் போகலாமா', keepHolding: 'பேசும்வரை அழுத்திப் பிடியுங்கள்', holding: 'பிடித்துள்ளது — பேசுங்கள்',
    checking: 'உங்களுக்காக பார்க்கிறோம்', query: 'இன்று மீன்பிடிக்கப் போகலாமா?',
    composing: 'பதில் தயாராகிறது', checkNote: 'கடல், வானிலை, கடல் எல்லை, உங்கள் படகு — எல்லாம் பார்க்கிறோம்.',
    advice: 'இன்று காலை அலைகள் கடுமை. சென்றால் பதினொன்றுக்குள் திரும்பி வாருங்கள்.',
    listenAgain: 'மீண்டும் கேட்க', why: 'ஏன் இப்படி?', evidence: 'இது எங்கிருந்து?', values: 'மதிப்புகள்',
    waveL: 'அலை உயரம்', windL: 'காற்று வேகம்', returnL: 'திரும்ப வேண்டும்',
    sum: 'மொத்தம்', scoreNote: 'எண் அதிகம் என்றால் ஆபத்து அதிகம்',
    band: '40 முதல் 69 = எச்சரிக்கை. போகலாம், ஆனால் சீக்கிரம் திரும்பவும்.',
    layers: 'எதைக் காட்ட', mapTitle: 'வரைபடம்', tapZone: 'ஒரு எண்ணைத் தொடவும்', forecast: 'இன்று பிறகு',
    profile: 'என் படகு', boatType: 'ஃபைபர் படகு', boatNote: 'இந்தப் படகுக்கேற்ப ஆலோசனை. மாற்றம் இருந்தால் திருத்தவும்.',
    language: 'மொழி', emergency: 'அவசரம்', zoneName: 'இடம் 1 · கிழக்குப் பாறை', topPick: 'இன்றைய சிறந்த இடம்',
    route: 'வழி காட்டு',
    voiceNote: 'ஒடியா, வங்காளத்திற்கு குரல் இல்லை. பதில் பெரிய எழுத்தில் காட்டப்படும்.',
    tripCache: 'இந்தப் பயணத்தை சேமிக்கவும்', downloadTrip: 'பயணத்தை சேமி', bundledTiles: 'சேமித்த வரைபடம் — இணையம் தேவையில்லை',
    offline: 'இணையம் இல்லை', lastUpdate: '40 நிமிடம் முன் புதுப்பிப்பு',
    geoTitle: 'எல்லை எச்சரிக்கை', geoBody: 'நீங்கள் கடல் எல்லைக்கு அருகில் உள்ளீர்கள். உடனே மேற்கே திரும்பவும்.',
    toBoundary: 'எல்லை தூரம்', bearing: 'திசை', ack: 'புரிந்தது — மேற்கே திரும்புகிறேன்',
    noDismiss: 'பொத்தானை அழுத்தும் வரை இது இருக்கும்.',
    worksOffline: 'இணையம் இன்றி வேலை செய்யும்', position: 'நீங்கள் இப்போது இருக்கும் இடம்',
    nearestHarbour: 'அருகிலுள்ள துறைமுகம்', harbourName: 'விசாகப்பட்டினம் மீன்பிடி துறைமுகம்'
  },
  hi: {
    go: "जा सकते हैं",
    goAdvice: "आज समुद्र शांत है। जा सकते हैं, शाम तक रह सकते हैं।",
    seaNow: "अभी का समुद्र",
    trips: "मेरी यात्राएँ",
    lastTrips: "पिछले ३० दिन",
    tripsHint: "मौसम देखने के लिए यात्रा दबाएँ",
    hoursOut: "घंटे बाहर",
    catchLog: "पकड़ दर्ज",
    addTrip: "आज की यात्रा जोड़ें",
    tagline: 'समुद्र सुरक्षा सलाह', langNative: 'हिन्दी', loc: 'विशाखापत्तनम तट',
    online: 'जुड़ा है · जानकारी ताज़ा है', updatedNow: '२ मिनट पहले अपडेट',
    caution: 'सावधान', askOrTap: 'सवाल पूछें, या नीचे एक चुनें',
    hold: 'बोलने के लिए दबाकर रखें', type: 'टाइप', listening: 'सुन रहे हैं', youSaid: 'आप कह रहे हैं',
    heard: 'क्या आज मछली पकड़ने जाऊँ', keepHolding: 'बोलते समय दबाए रखें', holding: 'दबा हुआ है — बोलिए',
    checking: 'आपके लिए देख रहे हैं', query: 'क्या आज मछली पकड़ने जाऊँ?',
    composing: 'उत्तर तैयार हो रहा है', checkNote: 'समुद्र, मौसम, समुद्री सीमा और आपकी नाव — सब देखते हैं।',
    advice: 'आज सुबह लहरें तेज़ हैं। जाएँ तो ग्यारह बजे से पहले लौट आएँ।',
    listenAgain: 'फिर सुनें', why: 'ऐसा क्यों?', evidence: 'यह कहाँ से आया?', values: 'मान',
    waveL: 'लहर ऊँचाई', windL: 'हवा की गति', returnL: 'वापस आएँ',
    sum: 'कुल', scoreNote: 'संख्या ज़्यादा मतलब ख़तरा ज़्यादा',
    band: '४० से ६९ = सावधान. जा सकते हैं, पर जल्दी लौटें.',
    layers: 'क्या दिखाएँ', mapTitle: 'नक्शा', tapZone: 'एक नंबर दबाएँ', forecast: 'आज आगे',
    profile: 'मेरी नाव', boatType: 'फ़ाइबर नाव', boatNote: 'सलाह इसी नाव के हिसाब से है। बदलाव हो तो सुधारें।',
    language: 'भाषा', emergency: 'आपातकाल', zoneName: 'जगह १ · पूर्वी चट्टान', topPick: 'आज की सबसे अच्छी जगह',
    route: 'रास्ता दिखाएँ',
    voiceNote: 'ओड़िया और बांग्ला में आवाज़ नहीं है। उत्तर बड़े अक्षरों में दिखेगा।',
    tripCache: 'यह यात्रा फ़ोन में सहेजें', downloadTrip: 'यात्रा सहेजें', bundledTiles: 'सहेजा नक्शा — इंटरनेट ज़रूरी नहीं',
    offline: 'इंटरनेट नहीं है', lastUpdate: '४० मिनट पहले अपडेट',
    geoTitle: 'सीमा चेतावनी', geoBody: 'आप समुद्री सीमा के पास हैं। तुरंत पश्चिम की ओर लौटें।',
    toBoundary: 'सीमा तक', bearing: 'दिशा', ack: 'समझ गया — पश्चिम लौटता हूँ',
    noDismiss: 'बटन दबाने तक यह संदेश रहेगा।',
    worksOffline: 'बिना इंटरनेट चलता है', position: 'आप अभी यहाँ हैं',
    nearestHarbour: 'निकटतम बंदरगाह', harbourName: 'विशाखापत्तनम मछली बंदरगाह'
  }
} as const;

export const ASKS = {
  en: ['Can I go out today?', 'Where are the fish?', 'How big are the waves?', 'When should I come back?'],
  te: ['ఈరోజు వెళ్లొచ్చా?', 'చేపలు ఎక్కడ ఉన్నాయి?', 'అలలు ఎంత ఉన్నాయి?', 'ఎప్పుడు తిరిగి రావాలి?'],
  ta: ['இன்று போகலாமா?', 'மீன் எங்கே இருக்கு?', 'அலை எவ்வளவு?', 'எப்போது திரும்ப வேண்டும்?'],
  hi: ['क्या आज जाऊँ?', 'मछली कहाँ है?', 'लहरें कितनी बड़ी हैं?', 'कब लौटना चाहिए?']
} as const;

export const CHECKS = {
  en: [['The sea', 'Waves and currents'], ['The weather', 'Wind for today'], ['The sea border', 'You are inside Indian waters'], ['Your boat', 'What is safe for a 9.2 m fibre boat']],
  te: [['సముద్రం', 'అలలు, ప్రవాహం'], ['వాతావరణం', 'ఈరోజు గాలి'], ['సముద్ర సరిహద్దు', 'మీరు భారత జలాల్లో ఉన్నారు'], ['మీ పడవ', '౯.౨ మీ ఫైబర్ పడవకు ఏది సురక్షితం']],
  ta: [['கடல்', 'அலை, நீரோட்டம்'], ['வானிலை', 'இன்றைய காற்று'], ['கடல் எல்லை', 'நீங்கள் இந்திய கடலில் உள்ளீர்கள்'], ['உங்கள் படகு', '9.2 மீ படகுக்கு பாதுகாப்பானது எது']],
  hi: [['समुद्र', 'लहरें और धारा'], ['मौसम', 'आज की हवा'], ['समुद्री सीमा', 'आप भारतीय जल में हैं'], ['आपकी नाव', '९.२ मी नाव के लिए क्या सुरक्षित है']]
} as const;

export const EV_LABELS = {
  en: ['Wave height', 'Wind speed', 'Sea temperature', 'Fish signs (chlorophyll)', 'Storm chance', 'Sea border line'],
  te: ['అల ఎత్తు', 'గాలి వేగం', 'సముద్ర ఉష్ణోగ్రత', 'చేపల సూచన', 'తుఫాను అవకాశం', 'సరిహద్దు రేఖ'],
  ta: ['அலை உயரம்', 'காற்று வேகம்', 'கடல் வெப்பம்', 'மீன் அறிகுறி', 'புயல் வாய்ப்பு', 'கடல் எல்லைக் கோடு'],
  hi: ['लहर ऊँचाई', 'हवा की गति', 'समुद्र तापमान', 'मछली के संकेत', 'तूफ़ान की संभावना', 'सीमा रेखा']
} as const;

export const NOT_MEASURED = { en: 'Not measured', te: 'కొలవలేదు', ta: 'அளக்கவில்லை', hi: 'मापा नहीं' } as const;

export const TIER_WORD = {
  en: { A: 'ISRO satellite', B: 'Government service', C: 'Backup source' },
  te: { A: 'ఇస్రో ఉపగ్రహం', B: 'ప్రభుత్వ సేవ', C: 'ప్రత్యామ్నాయ మూలం' },
  ta: { A: 'இஸ்ரோ செயற்கைக்கோள்', B: 'அரசு சேவை', C: 'மாற்று ஆதாரம்' },
  hi: { A: 'इसरो उपग्रह', B: 'सरकारी सेवा', C: 'वैकल्पिक स्रोत' }
} as const;

export const LAYERS = {
  en: ['Fishing spots', 'Protected areas', 'Coral and reefs', 'Sea border', 'Depth'],
  te: ['చేపల స్థలాలు', 'రక్షిత ప్రాంతాలు', 'పగడపు దిబ్బలు', 'సముద్ర సరిహద్దు', 'లోతు'],
  ta: ['மீன்பிடி இடங்கள்', 'பாதுகாக்கப்பட்ட பகுதி', 'பவளப்பாறை', 'கடல் எல்லை', 'ஆழம்'],
  hi: ['मछली की जगह', 'संरक्षित क्षेत्र', 'मूंगा चट्टान', 'समुद्री सीमा', 'गहराई']
} as const;

export const VESSEL_L = {
  en: ['Length', 'Speed', 'Safe wave', 'Range', 'Fuel', 'Crew'],
  te: ['పొడవు', 'వేగం', 'సురక్షిత అల', 'పరిధి', 'ఇంధనం', 'సిబ్బంది'],
  ta: ['நீளம்', 'வேகம்', 'பாதுகாப்பு அலை', 'வரம்பு', 'எரிபொருள்', 'பணியாளர்'],
  hi: ['लंबाई', 'गति', 'सुरक्षित लहर', 'सीमा', 'ईंधन', 'चालक दल']
} as const;

export const PROFILE_ROWS = {
  en: [['My places', 'Home harbour and two fishing grounds'], ['My trips', '12 trips in the last month'], ['Emergency numbers', 'Coast Guard, family, harbour']],
  te: [['నా స్థలాలు', 'ఇంటి రేవు, రెండు వేట స్థలాలు'], ['నా ప్రయాణాలు', 'గత నెలలో ౧౨ ప్రయాణాలు'], ['అత్యవసర నంబర్లు', 'కోస్ట్ గార్డ్, కుటుంబం, రేవు']],
  ta: [['என் இடங்கள்', 'வீட்டுத் துறைமுகம், இரு மீன்பிடி இடம்'], ['என் பயணங்கள்', 'கடந்த மாதம் 12 பயணம்'], ['அவசர எண்கள்', 'கடலோர காவல், குடும்பம், துறைமுகம்']],
  hi: [['मेरी जगहें', 'घर बंदरगाह और दो मछली स्थल'], ['मेरी यात्राएँ', 'पिछले महीने १२ यात्राएँ'], ['आपात नंबर', 'तटरक्षक, परिवार, बंदरगाह']]
} as const;

export const CACHE_ITEMS = {
  en: [['Map for this area', '18 MB'], ['Weather for 24 hours', '2 MB'], ['Sea border lines', '1 MB'], ['Your route', '0.4 MB'], ['Emergency numbers', '0.1 MB']],
  te: [['ఈ ప్రాంత మ్యాప్', '18 MB'], ['౨౪ గంటల వాతావరణం', '2 MB'], ['సరిహద్దు రేఖలు', '1 MB'], ['మీ దారి', '0.4 MB'], ['అత్యవసర నంబర్లు', '0.1 MB']],
  ta: [['இப்பகுதி வரைபடம்', '18 MB'], ['24 மணி வானிலை', '2 MB'], ['எல்லைக் கோடுகள்', '1 MB'], ['உங்கள் வழி', '0.4 MB'], ['அவசர எண்கள்', '0.1 MB']],
  hi: [['इस इलाके का नक्शा', '18 MB'], ['२४ घंटे का मौसम', '2 MB'], ['सीमा रेखाएँ', '1 MB'], ['आपका रास्ता', '0.4 MB'], ['आपात नंबर', '0.1 MB']]
} as const;

export const CONTACTS = {
  en: [['Coast Guard', '1554', 'CALL'], ['Marine Police', '100', 'CALL'], ['Harbour office', '0891 256 1234', 'CALL'], ['Family — Lakshmi', '+91 98480 11223', 'SMS']],
  te: [['కోస్ట్ గార్డ్', '1554', 'కాల్'], ['మెరైన్ పోలీస్', '100', 'కాల్'], ['రేవు కార్యాలయం', '0891 256 1234', 'కాల్'], ['కుటుంబం — లక్ష్మి', '+91 98480 11223', 'SMS']],
  ta: [['கடலோர காவல்', '1554', 'அழை'], ['கடல் காவல்துறை', '100', 'அழை'], ['துறைமுக அலுவலகம்', '0891 256 1234', 'அழை'], ['குடும்பம் — லட்சுமி', '+91 98480 11223', 'SMS']],
  hi: [['तटरक्षक', '1554', 'कॉल'], ['समुद्री पुलिस', '100', 'कॉल'], ['बंदरगाह कार्यालय', '0891 256 1234', 'कॉल'], ['परिवार — लक्ष्मी', '+91 98480 11223', 'SMS']]
} as const;

export const TABS = {
  en: ['Ask', 'Map', 'Trips', 'My boat'],
  te: ['అడగండి', 'మ్యాప్', 'ప్రయాణాలు', 'నా పడవ'],
  ta: ['கேள்', 'வரைபடம்', 'பயணம்', 'என் படகு'],
  hi: ['पूछें', 'नक्शा', 'यात्राएँ', 'मेरी नाव']
} as const;

export const LANGS = [
  { code: 'en', native: 'English', roman: 'English', voice: true },
  { code: 'te', native: 'తెలుగు', roman: 'Telugu', voice: true },
  { code: 'ta', native: 'தமிழ்', roman: 'Tamil', voice: true },
  { code: 'hi', native: 'हिन्दी', roman: 'Hindi', voice: true },
  { code: 'or', native: 'ଓଡ଼ିଆ', roman: 'Odia', voice: false },
  { code: 'ml', native: 'മലയാളം', roman: 'Malayalam', voice: true },
  { code: 'kn', native: 'ಕನ್ನಡ', roman: 'Kannada', voice: true },
  { code: 'bn', native: 'বাংলা', roman: 'Bengali', voice: false }
] as const;
